name: Deploy Hugo site
on:
  push:
    branches: ["master"]
permissions:
  contents: read          # allow repo read (needed for private modules)
  pages: write            # allow Pages deployment
  id-token: write         # allow OIDC for Pages
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/HugoBlox/all-access    # mark private module
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false   # don't use default token for Git operations
          fetch-depth: 0

      - name: Authenticate Git for private modules
        env:
          GH_PAT: ${{ secrets.GH_PAT }}            # GitHub PAT stored in secrets
        run: git config --global url."https://${GH_PAT}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Download Go modules
        run: go mod download

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.WC_HUGO_VERSION }}
          extended: true

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
        run: hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write          # allow deployment to pages
      id-token: write       # allow OIDC auth for pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
